(ns #^{:doc "Problem 28"
       :author "Alexander Dovzhikov"}
  dan.euler.problem029)

(comment "
Consider all integer combinations of ab for 2  a  5 and 2  b  5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?")

; this function is not used here
(defn factorial
  "Returns n!"
  [n]
  (loop [k n acc 1]
    (if (= k 1)
      acc
      (recur (dec k) (* k acc)))))

(defn pow
  "Returns x to the power of y"
  [x y]
  (loop [a x b y acc 1]
    (if (zero? b)
      acc
      (recur a (dec b) (* a acc)))))

(defn problem29
  "Solves problem 27 of Project Euler and returns the result"
  []
  (count (distinct (for [a (range 2 101) b (range 2 101)] (pow a b)))))

(println "[Problem029]:" (time (problem29)))
